# Explore Separate Analysis

This notebook reads and displays the contents of the `separate-analysis.pickle` file.

In [1]:
import pickle
import sys

# Add the common module path
sys.path.append('../volume-1/common')
from settings import ANALYSIS_RELATIVE_FILEPATH, SEPARATE_ANALYSIS_FILENAME, AGGREGATE_ANALYSIS_FILENAME

In [2]:
# Read the separate analysis pickle file
filepath = f'{ANALYSIS_RELATIVE_FILEPATH}/{SEPARATE_ANALYSIS_FILENAME}'
print(f'Reading from: {filepath}')

with open(filepath, 'rb') as file_in:
    separate_analysis = pickle.load(file_in)

print(f'Type: {type(separate_analysis)}')

Reading from: ../volume-1/data-analysis/separate-analysis.pickle
Type: <class 'pandas.core.frame.DataFrame'>

In [3]:
# Print the object
separate_analysis

,feed_id,partner_feed_id,file_name,dataset_name,publisher_name,feed_url,dataset_url,discussion_url,license_url,logo_url,...,num_items,num_analysis_items,num_partnered_items,num_unpartnered_items,num_opportunity_start_dates,num_future_opportunity_start_dates,num_future_week_opportunity_start_dates,num_opportunity_items,num_future_opportunity_items,num_future_week_opportunity_items
0,api-schools-plus-co-uk-api-oa-facility-uses,api-schools-plus-co-uk-api-oa-slots,preview-ops--api-schools-plus-co-uk-api-oa-fac...,Schools Plus Ltd Facilities,Schools Plus Ltd,https://api.schools-plus.co.uk/api/oa/facility...,http://www.schools-plus.co.uk/OpenActive.php,https://github.com/jeremyswright/opendata,https://creativecommons.org/licenses/by/4.0/,https://www.schoolsplus.co.uk/wp-content/theme...,...,4059,3732,327,3732,0,0,0,0,0,0
1,api-schools-plus-co-uk-api-oa-slots,api-schools-plus-co-uk-api-oa-facility-uses,preview-ops--api-schools-plus-co-uk-api-oa-slo...,Schools Plus Ltd Facilities,Schools Plus Ltd,https://api.schools-plus.co.uk/api/oa/slots,http://www.schools-plus.co.uk/OpenActive.php,https://github.com/jeremyswright/opendata,https://creativecommons.org/licenses/by/4.0/,https://www.schoolsplus.co.uk/wp-content/theme...,...,287412,287412,177633,109779,287412,15672,8208,287412,15672,8208
2,betterflow-coursepro-co-uk-odi-scheduled-sessions,betterflow-coursepro-co-uk-odi-session-series,preview-ops--betterflow-coursepro-co-uk-odi-sc...,Better Sessions,Better,https://betterflow.coursepro.co.uk/odi/schedul...,https://betterflow.coursepro.co.uk/odi/feed,https://github.com/FitronicsOpenActive/betterf...,https://creativecommons.org/licenses/by/4.0/,http://data.better.org.uk/images/logo.png,...,86464,86464,0,86464,86464,24418,803,86464,24418,803
3,betterflow-coursepro-co-uk-odi-session-series,betterflow-coursepro-co-uk-odi-scheduled-sessions,preview-ops--betterflow-coursepro-co-uk-odi-se...,Better Sessions,Better,https://betterflow.coursepro.co.uk/odi/session...,https://betterflow.coursepro.co.uk/odi/feed,https://github.com/FitronicsOpenActive/betterf...,https://creativecommons.org/licenses/by/4.0/,http://data.better.org.uk/images/logo.png,...,914,914,0,914,0,0,0,0,0,0
4,actihire-bookteq-com-api-open-active-facility-...,actihire-bookteq-com-api-open-active-slots,regular-ops--actihire-bookteq-com-api-open-act...,Actihire Facilities,Actihire,https://actihire.bookteq.com/api/open-active/f...,https://actihire.bookteq.com/api/open-active,https://github.com/playfinder/openactive/issues,https://creativecommons.org/licenses/by/4.0/,https://s3.eu-west-2.amazonaws.com/cdn.bookteq...,...,876,124,752,124,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,wycliffecollege-bookteq-com-api-open-active-fa...,wycliffecollege-bookteq-com-api-open-active-slots,regular-ops--wycliffecollege-bookteq-com-api-o...,Wycliffe College Facilities,Wycliffe College,https://wycliffecollege.bookteq.com/api/open-a...,https://wycliffecollege.bookteq.com/api/open-a...,https://github.com/playfinder/openactive/issues,https://creativecommons.org/licenses/by/4.0/,https://s3.eu-west-2.amazonaws.com/cdn.bookteq...,...,21,4,17,4,0,0,0,0,0,0
476,wycliffecollege-bookteq-com-api-open-active-slots,wycliffecollege-bookteq-com-api-open-active-fa...,regular-ops--wycliffecollege-bookteq-com-api-o...,Wycliffe College Facilities,Wycliffe College,https://wycliffecollege.bookteq.com/api/open-a...,https://wycliffecollege.bookteq.com/api/open-a...,https://github.com/playfinder/openactive/issues,https://creativecommons.org/licenses/by/4.0/,https://s3.eu-west-2.amazonaws.com/cdn.bookteq...,...,92686,92686,92285,401,92686,77040,1444,92686,77040,1444
477,wymondhamtownunitedfc-bookteq-com-api-open-act...,wymondhamtownunitedfc-bookteq-com-api-open-act...,regular-ops--wymondhamtownunitedfc-bookteq-com...,Wymondham Town United FC Facilities,Wymondham Town United FC,https://wymondhamtownunitedfc.bookteq.com/api/...,https://wymondhamtownunitedfc.bookteq.com/api/...,https://github.com/playfinder/openactive/issues,https://creativecommons.org/licenses/by/4.0/,https://s3.eu-west-2.amazonaws.com/cdn.bookteq...,...,20,0,20,0,0,0,0,0,0,0
478,wymondhamtownunitedfc-bookteq-com-api-open-act...,wymondhamtownunitedfc-bookteq-com-api-open-act...,regular-ops--wymondhamtownunitedfc-bookteq-com...,Wymondham Town United FC Facilities,Wymondham Town United FC,https://wymondhamtownunitedfc.bookteq.com/api/...,https://wymondhamtownunitedfc.bookteq.com/api/...,https://github.com/playfinder/openactive/issues,https://creativecommons.org/licenses/by/4.0/,https://s3.eu-west-2.amazonaws.com/cdn.bookteq...,...,20017,20017,20017,0,20017,19324,1008,20017,19324,1008
479,ymcahumber-bookteq-com-api-open-active-facilit...,None,regular-ops--ymcahumber-bookteq-com-api-open-a...,Clee Fields Facilities,Clee Fields,https://ymcahumber.bookteq.com/api/open-active...,https://ymcahumber.bookteq.com/api/open-active,https://github.com/playfinder/openactive/issues,https://creativecommons.org/licenses/by/4.0/,https://s3.eu-west-2.amazonaws.com/cdn.bookteq...,...,16,16,None,None,0,0,0,0,0,0

In [4]:
filepath = f'{ANALYSIS_RELATIVE_FILEPATH}/{AGGREGATE_ANALYSIS_FILENAME}'
print(f'Reading from: {filepath}')

with open(filepath, 'rb') as file_in:
    aggregate_analysis = pickle.load(file_in)

print(f'Type: {type(aggregate_analysis)}')

Reading from: ../volume-1/data-analysis/aggregate-analysis.pickle
Type: <class 'dict'>

In [5]:
aggregate_analysis['gdf_total_districts_counts'][['LAD24NM', 'count', 'percentage']]

                  LAD24NM    count  percentage
0              Hartlepool    370.0    0.002609
1           Middlesbrough  37976.0    0.267790
2    Redcar and Cleveland  61422.0    0.433122
3        Stockton-on-Tees    766.0    0.005402
4              Darlington   2112.0    0.014893
..                    ...      ...         ...
356               Torfaen  14736.0    0.103912
357         Monmouthshire    930.0    0.006558
358               Newport   1276.0    0.008998
359                 Powys   9895.0    0.069775
360        Merthyr Tydfil  14247.0    0.100464

[361 rows x 3 columns]

In [10]:
gp_counts= aggregate_analysis['gdf_total_gps_counts'][['Name', 'count', 'percentage']]
gp_counts

                                                 Name    count  percentage
0     B81061 - BROUGH AND SOUTH CAVE MEDICAL PRACTICE    719.0    0.005070
1                       C85628 - CAXTON HOUSE SURGERY  33304.0    0.234846
2                               C81031 - PARK SURGERY   7655.0    0.053980
3                     C86001 - CARCROFT DOCTORS GROUP    105.0    0.000740
4                        C81032 - SWADLINCOTE SURGERY  14037.0    0.098983
...                                               ...      ...         ...
7667                                         Y05330 -      NaN         NaN
7668                                         Y05346 -      NaN         NaN
7669                                         Y05349 -      2.0    0.000014
7670                                         Y05369 -      NaN         NaN
7671                                         Z84653 -      NaN         NaN

[7672 rows x 3 columns]

In [11]:
gp_counts.to_csv("./output/gp_counts.csv", index=False)

In [12]:
parish_counts= aggregate_analysis['gdf_total_parishes_counts'][['PARNCP25NM', 'count', 'percentage']]
parish_counts

           PARNCP25NM    count  percentage
0            Blackrod      NaN         NaN
1             Horwich  14206.0    0.100175
2        Westhoughton   2220.0    0.015654
3             Ringway      NaN         NaN
4         Saddleworth    669.0    0.004718
...               ...      ...         ...
11534      Wye Valley      NaN         NaN
11535  Llanelli Rural     16.0    0.000113
11536    Llangyndeyrn      NaN         NaN
11537      Pontyberem      NaN         NaN
11538       Trimsaran      NaN         NaN

[11539 rows x 3 columns]

In [13]:
parish_counts.to_csv("./output/parish_counts.csv", index=False)

In [14]:
aggregate_analysis

{'num_publishers_regular': 158,
 'num_publishers_preview': 2,
 'num_publishers': 159,
 'num_datasets_regular': 175,
 'num_datasets_preview': 2,
 'num_datasets': 177,
 'num_feeds_regular': 464,
 'num_feeds_preview': 6,
 'num_feeds': 470,
 'num_feeds_with_analysed_data_regular': 472,
 'num_feeds_with_analysed_data_preview': 4,
 'num_feeds_with_analysed_data': 476,
 'num_feeds_with_future_opportunity_items_regular': 220,
 'num_feeds_with_future_opportunity_items_preview': 2,
 'num_feeds_with_future_opportunity_items': 222,
 'total_num_items_regular': np.int64(13993251),
 'total_num_items_preview': np.int64(359189),
 'total_num_items': np.int64(14352440),
 'total_num_future_opportunity_items_regular': np.int64(9326207),
 'total_num_future_opportunity_items_preview': np.int64(41060),
 'total_num_future_opportunity_items': np.int64(9367267),
 'total_num_future_week_opportunity_items_regular': np.int64(1608579),
 'total_num_future_week_opportunity_items_preview': np.int64(9002),
 'total_num_future_week_opportunity_items': np.int64(1617581),
 'df_total_item_kinds_counts':                          item_kind    count  percentage
 0       IndividualFacilityUse/Slot  6852035   47.741255
 1                 FacilityUse/Slot  3253904   22.671434
 2                 ScheduledSession  1981550   13.806363
 3                 FacilityUse.Slot   716122    4.989549
 4                            Event   582025    4.055234
 5   ScheduledSession.SessionSeries   548968    3.824911
 6                    SessionSeries   172499    1.201879
 7                            event   117000    0.815192
 8                          session    56584    0.394247
 9                   CourseInstance    28870    0.201150
 10                         Session    22563    0.157207
 11                     FacilityUse    14139    0.098513
 12           IndividualFacilityUse     3681    0.025647
 13                          league     2148    0.014966
 14                   OnDemandEvent      352    0.002453,
 'total_num_item_kinds': 15,
 'total_num_items_with_kinds': np.int64(14352440),
 'df_total_item_types_counts':                item_type     count  percentage
 0                   Slot  10822061   75.402238
 1       ScheduledSession   2530518   17.631274
 2                  Event    713480    4.971141
 3          SessionSeries    172499    1.201879
 4                   None     58982    0.410955
 5         CourseInstance     28870    0.201150
 6            FacilityUse     13889    0.096771
 7          HeadlineEvent      8108    0.056492
 8  IndividualFacilityUse      3681    0.025647
 9          OnDemandEvent       352    0.002453,
 'total_num_item_types': 10,
 'total_num_items_with_types': np.int64(14352440),
 'df_total_organizer_names_counts':                   organizer     count  percentage
 0                      None  11096608   78.248525
 1                    Better   1386364    9.776045
 2           Everyone Active    296025    2.087441
 3              Halo Leisure    125222    0.883012
 4           British Cycling    100929    0.711708
 ...                     ...       ...         ...
 4809  Dominic Santarcangelo         1    0.000007
 4810                 Info30         1    0.000007
 4811            Shwetaom108         1    0.000007
 4812              Beverley1         1    0.000007
 4813     Goodgym Colchester         1    0.000007

 [4814 rows x 3 columns],
 'total_num_organizer_names': 4814,
 'total_num_items_with_organizer_names': np.int64(14181236),
 'df_total_activities_counts':                   activity    count  percentage
 0                     None  8724981   58.769883
 1                 Swimming   759744    5.117497
 2         Swimming Lessons   636046    4.284290
 3              Gym Workout   628662    4.234553
 4        Personal Training   597987    4.027932
 ...                    ...      ...         ...
 1429        Tumbling Class        1    0.000007
 1430  Body Weight Insanity        1    0.000007
 1431         Methodology X        1    0.000007
 1432               Camping        1    0.000007
 1433       Fitness Welcome        1    0.000007

 [1434 rows x 3 columns],
 'total_num_activities': 1434,
 'total_num_items_with_activities': np.int64(14846007),
 'df_total_facilities_counts':                 facility    count  percentage
 0                   None  8624251   60.814523
 1            Sports Hall  5554908   39.170831
 2              Gymnasium      982    0.006925
 3           Tennis Court      415    0.002926
 4        Badminton Court      203    0.001431
 5       Pickleball Court      137    0.000966
 6     Table Tennis Table      129    0.000910
 7         Football Pitch       97    0.000684
 8           Squash Court       45    0.000317
 9       Basketball Court       29    0.000204
 10       Athletics Track       21    0.000148
 11          Futsal Court        5    0.000035
 12         Cricket Pitch        4    0.000028
 13      Volleyball Court        2    0.000014
 14         Netball Court        2    0.000014
 15     Racquetball Court        2    0.000014
 16  Multi Use Games Area        1    0.000007
 17           Cricket Net        1    0.000007
 18           Rugby Pitch        1    0.000007
 19           Golf Course        1    0.000007,
 'total_num_facilities': 20,
 'total_num_items_with_facilities': np.int64(14181236),
 'df_total_activitiesfacilities_counts':                activity    count  percentage
 1435        Sports Hall  5554908   47.567244
 1              Swimming   759744    6.505765
 2      Swimming Lessons   636046    5.446527
 3           Gym Workout   628662    5.383297
 4     Personal Training   597987    5.120624
 ...                 ...      ...         ...
 1404       Jazz Fitness        1    0.000009
 1403        Break Dance        1    0.000009
 1402         Nerf Games        1    0.000009
 1401        Snorkelling        1    0.000009
 1453        Golf Course        1    0.000009

 [1452 rows x 3 columns],
 'df_total_accessibilities_counts':                     accessibility     count  percentage
 0                            None  14170109   99.700156
 1             Physical impairment      8347    0.058729
 2             Learning impairment      8251    0.058054
 3              Hearing impairment      7204    0.050687
 4            Mental health issues      6835    0.048091
 5               Visual impairment      6131    0.043137
 6  Social or behavioural problems      5466    0.038458
 7               Visual Impairment       382    0.002688,
 'total_num_accessibilities': 8,
 'total_num_items_with_accessibilities': np.int64(14212725),
 'gdf_total_regions_counts':     OBJECTID    eer18cd                   eer18nm   bng_e   bng_n      long  \
 0          1  E15000001                North East  417313  600358 -1.728900
 1          2  E15000002                North West  350015  506280 -2.772370
 2          3  E15000003  Yorkshire and The Humber  446903  448736 -1.287120
 3          4  E15000004             East Midlands  477660  322635 -0.849670
 4          5  E15000005             West Midlands  386294  295477 -2.203580
 5          6  E15000006                   Eastern  571074  263229  0.504146
 6          7  E15000007                    London  517516  178392 -0.308640
 7          8  E15000008                South East  470062  172924 -0.993110
 8          9  E15000009                South West  285015  102567 -3.633430
 9         10  N07000001          Northern Ireland   86601  535325 -6.854810
 10        11  S15000001                  Scotland  277746  700060 -3.970910
 11        12  W08000001                     Wales  263406  242881 -3.994160

           lat                              GlobalID  \
 0   55.297031  fbbc6e4d-8fd6-4719-a21d-49b62ff3af9b
 1   54.449451  89a00d05-0013-4ac5-9db3-035c06600433
 2   53.932640  ccc57252-deb9-48dd-85b0-d31e38682574
 3   52.795719  68dfd43b-2798-4f85-a7db-bcc09b13b44c
 4   52.556969  faba9cae-a323-43f9-9142-59832d9518c8
 5   52.240669  6c52d2ea-adcc-4bc2-ba81-1d77836b1b6c
 6   51.492271  8cf27884-40aa-4804-9f94-758865bfbee2
 7   51.450970  d7b9d30b-0180-43e0-8cbf-ae0b0f22d42d
 8   50.811192  a8a5d8b2-7e5f-4682-a7f4-5081d4cd1acc
 9   54.614941  6c423802-bea1-4610-af4f-6e6f8cc218b6
 10  56.177429  519120ea-f839-4052-b679-12f7bec2f751
 11  52.067410  6d46d329-118e-425c-bbd1-c7aa074875ad

                                              geometry    count  percentage
 0   MULTIPOLYGON (((397943.5 657534.102, 401096 65...   312208    2.201557
 1   MULTIPOLYGON (((363823.401 578129.102, 364213....  1091735    7.698447
 2   MULTIPOLYGON (((479351.004 518706.501, 481340....   791082    5.578371
 3   POLYGON ((516022.702 412210.895, 515854.099 41...  1506850   10.625661
 4   POLYGON ((409402.998 365710.796, 412633.099 36...   771562    5.440725
 5   MULTIPOLYGON (((599964.098 346659.983, 610004....  1283019    9.047300
 6   POLYGON ((537543.796 199883.103, 537646.398 19...  2569930   18.122045
 7   MULTIPOLYGON (((493941.101 254585.705, 493776....  1696079   11.960022
 8   MULTIPOLYGON (((416007.596 246053.797, 417496....   937152    6.608394
 9   MULTIPOLYGON (((116908.524 602925.192, 119765....   116107    0.818737
 10  MULTIPOLYGON (((322071.699 973988.499, 324045....    52847    0.372654
 11  MULTIPOLYGON (((313501.1 382583.1, 315287.497 ...   243131    1.714456  ,
 'total_num_regions': 13,
 'total_num_items_with_regions': np.int64(14181236),
 'gdf_total_districts_counts':      FID    LAD24CD               LAD24NM        LAD24NMW   BNG_E   BNG_N  \
 0      1  E06000001            Hartlepool                  447161  531473
 1      2  E06000002         Middlesbrough                  451141  516887
 2      3  E06000003  Redcar and Cleveland                  464330  519596
 3      4  E06000004      Stockton-on-Tees                  444940  518179
 4      5  E06000005            Darlington                  428029  515648
 ..   ...        ...                   ...             ...     ...     ...
 356  357  W06000020               Torfaen         Torfaen  327459  200480
 357  358  W06000021         Monmouthshire       Sir Fynwy  337812  209231
 358  359  W06000022               Newport       Casnewydd  337897  187432
 359  360  W06000023                 Powys           Powys  302329  273254
 360  361  W06000024        Merthyr Tydfil  Merthyr Tudful  305916  206404

         LONG       LAT                              GlobalID  \
 0   -1.27017  54.67613  3f58aa35-9ea6-4001-a80f-8aab0e41313f
 1   -1.21099  54.54467  c5bc1c3e-111f-46db-8e41-362fbbc78d30
 2   -1.00656  54.56752  29afa1cb-8719-44c2-9906-38bc7bae2981
 3   -1.30664  54.55687  8ebb86c0-86bb-466e-ae7e-a832eeb755ff
 4   -1.56835  54.53534  bf2173db-02e1-4b58-9617-e775100f58ec
 ..       ...       ...                                   ...
 356 -3.05101  51.69836  0cf05ad3-d5b4-4034-aef6-391a4f42fdb9
 357 -2.90280  51.77827  46cfbd32-dcb3-4da1-a166-0f149baa4e24
 358 -2.89769  51.58231  2d467913-8823-4be7-9178-ced94fc0673a
 359 -3.43531  52.34863  1f185fde-3f8c-4e60-b45d-4fb0379a9a51
 360 -3.36425  51.74840  9925511b-44e7-4753-8da5-72e7e510b305

                                               geometry    count  percentage
 0    POLYGON ((448964.105 536757.184, 448986.025 53...    370.0    0.002609
 1    POLYGON ((451894.299 521145.303, 453997.697 51...  37976.0    0.267790
 2    POLYGON ((478232.947 518788.802, 477689.303 51...  61422.0    0.433122
 3    POLYGON ((452243.536 526335.188, 451711.3 5256...    766.0    0.005402
 4    POLYGON ((436388.002 522354.197, 437351.702 52...   2112.0    0.014893
 ..                                                 ...      ...         ...
 356  POLYGON ((333723 192653.903, 331617.797 192679...  14736.0    0.103912
 357  MULTIPOLYGON (((354639.302 191757.499, 354620....    930.0    0.006558
 358  POLYGON ((343091.268 184213.081, 339999.991 18...   1276.0    0.008998
 359  POLYGON ((322891.603 333139.299, 323688.497 33...   9895.0    0.069775
 360  POLYGON ((308057.304 211036.201, 308367.104 20...  14247.0    0.100464

 [361 rows x 12 columns],
 'total_num_districts': 361,
 'total_num_items_with_districts': np.int64(14181236),
 'gdf_total_parishes_counts':          FID PARNCP25CD      PARNCP25NM       PARNCP25NW    LAD25CD  \
 0          1  E04000001        Blackrod                   E08000001
 1          2  E04000002         Horwich                   E08000001
 2          3  E04000003    Westhoughton                   E08000001
 3          4  E04000004         Ringway                   E08000003
 4          5  E04000005     Saddleworth                   E08000004
 ...      ...        ...             ...              ...        ...
 11534  11535  W04001085      Wye Valley          Tyndyrn  W06000021
 11535  11536  W04001086  Llanelli Rural  Llanelli Wledig  W06000010
 11536  11537  W04001087    Llangyndeyrn     Llangyndeyrn  W06000010
 11537  11538  W04001088      Pontyberem       Pontyberem  W06000010
 11538  11539  W04001089       Trimsaran        Trimsaran  W06000010

                LAD25NM   BNG_E   BNG_N      LONG       LAT  \
 0               Bolton  361040  410661 -2.590063  53.59108
 1               Bolton  365741  411963 -2.519190  53.60312
 2               Bolton  365008  406179 -2.529617  53.55108
 3           Manchester  381192  384606 -2.284052  53.35801
 4               Oldham  400672  407034 -1.991324  53.55994
 ...                ...     ...     ...       ...       ...
 11534    Monmouthshire  352367  202350 -2.690908  51.71785
 11535  Carmarthenshire  251110  205106 -4.157097  51.72486
 11536  Carmarthenshire  246514  211382 -4.226358  51.78000
 11537  Carmarthenshire  250361  211039 -4.170487  51.77797
 11538  Carmarthenshire  244366  205326 -4.254758  51.72500

                                    GlobalID  \
 0      53deb6eb-64ca-447a-a82a-f1d7a288fd72
 1      a624ab45-71b6-492b-84eb-ba00d5b109b1
 2      40d53166-a89d-4dc4-ab33-9d7d41f6b646
 3      1251c396-e09b-4fc0-9243-1db44194f0a4
 4      6201fbff-ca79-456a-8cf3-397306b3eaad
 ...                                     ...
 11534  f2c4e38c-9da1-4cf9-bb50-74c34d6a1356
 11535  0fd6afd4-d42b-41e3-a53e-893866dd097b
 11536  5ec83f58-034f-4220-9f5c-5a46f429b351
 11537  a3ee798d-b8fc-40fe-8a79-2ccb1357e560
 11538  98ce3026-f917-45ce-bd96-d2a63ee1f609

                                                 geometry    count  percentage
 0      POLYGON ((-2.57002 53.59546, -2.55206 53.57918...      NaN         NaN
 1      POLYGON ((-2.51041 53.62636, -2.51702 53.61482...  14206.0    0.100175
 2      POLYGON ((-2.50025 53.53812, -2.50689 53.5388,...   2220.0    0.015654
 3      POLYGON ((-2.25894 53.35946, -2.26708 53.35057...      NaN         NaN
 4      POLYGON ((-2.00947 53.61678, -1.98165 53.58934...    669.0    0.004718
 ...                                                  ...      ...         ...
 11534  POLYGON ((-2.66951 51.74276, -2.67281 51.73589...      NaN         NaN
 11535  POLYGON ((-4.15637 51.75494, -4.13579 51.7337,...     16.0    0.000113
 11536  POLYGON ((-4.19895 51.82818, -4.18827 51.81998...      NaN         NaN
 11537  POLYGON ((-4.14134 51.79026, -4.13744 51.78694...      NaN         NaN
 11538  POLYGON ((-4.22845 51.72709, -4.21714 51.72568...      NaN         NaN

 [11539 rows x 14 columns],
 'total_num_parishes': 4359,
 'total_num_items_with_parishes': np.int64(14181236),
 'gdf_total_gps_counts':        FID                                             Name   Area_Km2  \
 0        1  B81061 - BROUGH AND SOUTH CAVE MEDICAL PRACTICE  449.91700
 1        2                    C85628 - CAXTON HOUSE SURGERY  331.62700
 2        3                            C81031 - PARK SURGERY   15.54270
 3        4                  C86001 - CARCROFT DOCTORS GROUP   69.77920
 4        5                     C81032 - SWADLINCOTE SURGERY   21.97230
 ...    ...                                              ...        ...
 7667  7669                                         Y05330 -    4.90032
 7668  7670                                         Y05346 -  227.14400
 7669  7671                                         Y05349 -  270.40700
 7670  7672                                         Y05369 -   27.66330
 7671  7673                                         Z84653 -    3.45114

      CCG_ODS_cd CCG_ONS_cd                                           CCG_name  \
 0           02Y  E38000052                   NHS East Riding of Yorkshire CCG
 1           02P  E38000006                                   NHS Barnsley CCG
 2           15M  E38000229  NHS Derby and Derbyshire Clinical Commissionin...
 3           02X  E38000044                                  NHS Doncaster CCG
 4           15M  E38000229  NHS Derby and Derbyshire Clinical Commissionin...
 ...         ...        ...                                                ...
 7667        93C  E38000240                       NHS North Central London CCG
 7668        02Q  E38000008                                  NHS Bassetlaw CCG
 7669        03N  E38000146                                  NHS Sheffield CCG
 7670        52R  E38000243             NHS Nottingham and Nottinghamshire CCG
 7671

      PCN_ODS_cd                              PCN_name PracticeCd  \
 0        U97785       River and Wolds East Riding PCN     B81061
 1        U16464                          Barnsley PCN     C85628
 2        U72812  Alfreton Ripley Crich and Heanor PCN     C81031
 3        U30587                   Doncaster North PCN     C86001
 4        U90656                       Swadlincote PCN     C81032
 ...         ...                                   ...        ...
 7667     U83168              Haringey - Welbourne PCN     Y05330
 7668     U05001                Larwood and Bawtry PCN     Y05346
 7669     U26996             Sheffield City Centre PCN     Y05349
 7670     U65095                            Newark PCN     Y05369
 7671

                            PracticeNm  \
 0           The Ridings Medical Group
 1                Caxton House Surgery
 2                        Park Surgery
 3           Great North Medical Group
 4                 Swadlincote Surgery
 ...                               ...
 7667  Tottenham Hale Medical Practice
 7668     Westwood Primary Care Centre
 7669             Clover City Practice
 7670                Balderton Surgery
 7671

                                                   Notes  \
 0
 1
 2
 3
 4
 ...                                                 ...
 7667  Potential outliers in either 2018/19 or 2019/2...
 7668
 7669
 7670
 7671                     No data for 2018/19 or 2019/20

                                                geometry    count  percentage
 0     POLYGON Z ((-0.64837 53.86457 0, -0.49181 53.7...    719.0    0.005070
 1     POLYGON Z ((-1.23047 53.69183 0, -1.23322 53.6...  33304.0    0.234846
 2     POLYGON Z ((-1.32111 53.01779 0, -1.32398 53.0...   7655.0    0.053980
 3     POLYGON Z ((-1.14464 53.60086 0, -1.1618 53.59...    105.0    0.000740
 4     POLYGON Z ((-1.60096 52.7753 0, -1.59291 52.77...  14037.0    0.098983
 ...                                                 ...      ...         ...
 7667  POLYGON Z ((-0.05369 51.58622 0, -0.05785 51.5...      NaN         NaN
 7668  POLYGON Z ((-1.00506 53.42564 0, -1.02269 53.2...      NaN         NaN
 7669  POLYGON Z ((-1.49314 53.43736 0, -1.42261 53.4...      2.0    0.000014
 7670  POLYGON Z ((-0.71789 53.0313 0, -0.73158 53.02...      NaN         NaN
 7671  POLYGON Z ((-0.62663 54.49186 0, -0.62139 54.4...      NaN         NaN

 [7672 rows x 14 columns],
 'total_num_gps': 2389,
 'total_num_items_with_gps': np.int64(14181236),
 'df_total_sad_counts':                activity    count  sport_and_discipline
 0           Sports Hall  5554908              No Match
 1              Swimming   759744              SWIMMING
 2      Swimming Lessons   636046              SWIMMING
 3           Gym Workout   628662  EXERCISE AND FITNESS
 4     Personal Training   597987  EXERCISE AND FITNESS
 ...                 ...      ...                   ...

In [6]:
df = aggregate_analysis['gdf_total_districts_counts']

df[df['LAD24NM'] == 'Blackburn with Darwen'][['LAD24NM', 'count', 'percentage']]

                 LAD24NM   count  percentage
7  Blackburn with Darwen  6570.0    0.046329